---
title   : "Quality Assurance Report"
subtitle: "Process Chains "
author  : "F.J. Padt"
date    : "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook:
    toc: yes
  pdf_document:
    highlight: tango
    toc: yes
    toc_depth: 4
editor_options: 
  chunk_output_type: inline
---

```{r setup}

# # Cleanse memory
# rm(list = ls())
# gc()

# parameters Settings
pXLSX    <- "RSPC-Schedule" 
pWSHT    <- TRUE
newfiles <- TRUE
BIDOCsrc <- normalizePath("~/../../GrandVision/SAP BI documentation - Documents/bi-doc/src/")

# KnitR SetUp location
KS   <- file.path("..", "00_Global", "KnitR_SetUp.R")

# Load functions
invisible(source(KS))

```

```{r LIS-BW-VB_APPLICATION, eval=FALSE, include=FALSE}
# SID.lng  <- c("RS1300", "RD1120","RU1300", "RA1300", "RP1300")
# SID.sht  <- substr(SID.lng, 1, 3)
 
dtLISO <- 
  fRead_and_Union(
    pType    = "R",
    pTable   = "TBTCO", 
    pOptions = list("STATUS  = 'S'", "AND", 
                   "JOBNAME  like 'LIS-BW-VB_APPLICATION_%'", "AND",  
                   "PERIODIC = 'X'"), 
    pFields  = list('JOBNAME' , 'JOBCOUNT' , 
                   'SDLSTRTDT', 'SDLSTRTTM', 
                   'PRDMINS'  , 'PRDHOURS' , 'PRDDAYS', 'PRDWEEKS' ,'PRDMONTHS',
                   'EVENTID'  , 'EVENTPARM',
                   'AUTHCKMAN'))

dtLISP <- 
  fRead_and_Union(
    pType    = "R",
    pTable   = "TBTCP", 
    pOptions = list("STATUS = 'P'", "AND", 
                    "JOBNAME like 'LIS-BW-VB_APPLICATION_%'"), 
    pFields  = list('JOBNAME' , 'JOBCOUNT', 'STEPCOUNT',
                    'PROGNAME', 'VARIANT' , 
                    'AUTHCKNAM'))

dtLISC <- 
  dtLISO[dtLISP, on = .(SYSTID, CLIENT, JOBNAME, JOBCOUNT),
          nomatch = NA]

dtLIS <- 
  dcast.data.table(
    data = dtLISC,
    formula = PROGNAME + SDLSTRTDT + SDLSTRTTM + PRDMINS ~ SYSTID,
    fun.aggregate = length,
    value.var = "SYSTID") %>%
  setcolorder(
    c("PROGNAME",  "SDLSTRTDT",  "SDLSTRTTM",  "PRDMINS", 
      "RD1", "RA1", "RU1", "RP1", "RS1")) %T>%
  View()

write.table(
  dtLIS, 
  file = paste0(BIDOCsrc, "LIS.csv"))

pXLSX    <- "LIS-JOBS" 
if (pWSHT == TRUE) {
  fWriteToSheet(
    dtLISC, 
    RES, pXLSX, "LIS", pAppend = FALSE )}
shell.exec(file.path(RES, paste0(pXLSX, ".xlsx")))


```

```{r CreateSchedule}
# SID.lng  <- c("BA1300") #, "BTP300", "BU1300")
# SID.lng  <- c("BS1300", "BD1100", "BU1300", "BA1300", "BP1300") 
# SID.sht  <- substr(SID.lng, 1, 3)
dtSAP_LOGON[ systid == "BS1", type := "BS"]

T1 <- Sys.time()

dtTBTCO <- 
  fRead_and_Union(
    pType    = "B",
    pTable   = "TBTCO", 
    pOptions = list("(STATUS = 'S' OR STATUS = 'Z')", "AND", 
                    "JOBNAME = 'BI_PROCESS_TRIGGER'"), 
    pFields  = list('JOBNAME'  , 'JOBCOUNT'  , 'STATUS'    , 'CHECKSTAT' ,  
                    'SDLSTRTDT', 'SDLSTRTTM' , 'LASTSTRTDT', 'LASTSTRTTM',
                    'PRDMINS'  , 'PRDHOURS'  , 'PRDDAYS'   , 'PRDWEEKS'  ,'PRDMONTHS',
                    'PERIODIC' , 'EVENTID'   , 'EVENTPARM',
                    'AUTHCKMAN', 'CALENDARID', 'PRDBEHAV'))

dtTBTCP <- 
  fRead_and_Union(
    pType    = "B",
    pTable   = "TBTCP", 
    pOptions = list("STATUS = 'P'", "AND", 
                    "JOBNAME = 'BI_PROCESS_TRIGGER'"), 
    pFields  = list('JOBNAME' , 'JOBCOUNT', 'STEPCOUNT',
                    'PROGNAME', 'VARIANT' , 
                    'AUTHCKNAM'))

dtTBTC <- 
  dtTBTCO[dtTBTCP, on = .(SYSTID, CLIENT, JOBNAME, JOBCOUNT),
          nomatch = NA]

rm(list = c("dtTBTCP", "dtTBTCO"))

dtVAR <- dtTBTC[!is.na(SDLSTRTDT), .(SYSTID, CLIENT, PROGNAME, VARIANT)]
dtVAR[, CHAIN := " "]

for (i in 1:nrow(dtVAR)) {
  dtVAR[i, CHAIN := 
          fGetChain(pSYSTID   = dtVAR[i, SYSTID],
                    pCLIENT   = dtVAR[i, CLIENT],
                    pPROGNAME = dtVAR[i, PROGNAME],
                    pVARIANT  = dtVAR[i, VARIANT])]
  print(paste(
    i                ,
    dtVAR[i, SYSTID] , 
    dtVAR[i, CLIENT] , 
    dtVAR[i, VARIANT], 
    dtVAR[i, CHAIN]  ,
    sep = "-"))
  
}

dtSCHED <- 
  dtVAR[dtTBTC, on = .(SYSTID, CLIENT, PROGNAME, VARIANT), nomatch = NA]

dtSCHED[, SDLSTRTTM := str_pad(
  string = SDLSTRTTM, width = 6, side = "left", pad = "0")]

dtSCHED[, SDLSTRTDT := ymd(SDLSTRTDT)]
dtSCHED[, SDLSTRTTM := paste(
  substr(SDLSTRTTM, 1, 2),
  substr(SDLSTRTTM, 3, 4),
  substr(SDLSTRTTM, 5, 6),
  sep = ":")]

Sys.time() - T1
# fCloseAllSAPConnections()

# Create Pivot
dtPIVOT <- 
  dcast.data.table(
    data = dtSCHED,
    formula = CHAIN + SDLSTRTDT + SDLSTRTTM + 
      PRDMINS + PRDHOURS + PRDDAYS + PRDWEEKS + PRDMONTHS ~ SYSTID,
    fun.aggregate = length,
    value.var = "SYSTID")                    %>%  
  .[, Total := BD1 + BA1 + BU1 + BP1]        %T>%
  setcolorder(
    c("CHAIN", "SDLSTRTDT", "SDLSTRTTM", "PRDMINS", "PRDHOURS", "PRDDAYS", "PRDWEEKS", "PRDMONTHS",
      "BD1", "BA1", "BU1", "BP1", "Total"))  %T>%
  View()

write.table(
  dtPIVOT, 
  file = paste0(BIDOCsrc, "RSPC.csv"),
  sep = ";", row.names = FALSE)
shell.exec(paste0(BIDOCsrc, "RSPC.csv"))

pXLSX    <- "RSPC-Schedule" 
if (pWSHT == TRUE) {
  fWriteToSheet(
    dtSCHED, 
    RES, pXLSX, "CHAINS", pAppend = FALSE )}
 shell.exec(file.path(RES, paste0(pXLSX, ".xlsx")))
 
```

```{r logs, eval=FALSE, include=FALSE}
# SID.lng  <- c("BA1300") #, "BTP300", "BU1300")
SID.lng  <- c("BS1300", "BD1100", "BU1300", "BA1300", "BP1300")
SID.sht  <- substr(SID.lng, 1, 3)
# 1ZPKVSZFBAED620WII5PLWLLP


# load(file.path("..", "..", "11_PrepData", "dtRSPCLOGCHAIN.RData"))
dtRSPCLOGCHAIN <- 
  read.fst(file.path("..", "..", "11_PrepData", "dtRSPCLOGCHAIN.fst"),
           as.data.table = TRUE) %>%
  .[DATUM < max(DATUM)]

cutOff <- format(max(dtRSPCLOGCHAIN$DATUM), "%Y%m%d")

dtRSPCLOGCHAIN_N  <-
  fReadSAPTable(
    pSystID  = "BP1",
    pClient  = "300", 
    pTable   = "RSPCLOGCHAIN",
    pOptions = list(paste0("DATUM > '", cutOff , "'")),
    pFields  = as.list(setdiff( names(dtRSPCLOGCHAIN), c("SYSTID", "CLIENT")))) %>%
  .[ , DATUM := ymd(DATUM)]

dtRSPCLOGCHAIN <- 
  rbindlist(
    list(dtRSPCLOGCHAIN, dtRSPCLOGCHAIN_N))
save(dtRSPCLOGCHAIN,      file = file.path("..", "..", "11_PrepData", "dtRSPCLOGCHAIN.RData"))
write.fst(dtRSPCLOGCHAIN, path = file.path("..", "..", "11_PrepData", "dtRSPCLOGCHAIN.fst"))

# load(file.path("..", "..", "11_PrepData", "dtRSPCPROCESSLOG.RData"))
dtRSPCPROCESSLOG <- 
  read.fst(file.path("..", "..", "11_PrepData", "dtRSPCPROCESSLOG.fst"),
           as.data.table = TRUE) %>%
  .[BATCHDATE < max(BATCHDATE)]

cutOff <- max(dtRSPCPROCESSLOG$BATCHDATE)

dtRSPCPROCESSLOG_N  <-
  fReadSAPTable(
    pSystID  = "BP1",
    pClient  = "300", 
    pTable   = "RSPCPROCESSLOG",
    pOptions = list(paste0("BATCHDATE > '", cutOff , "'")),
    pFields  = as.list(setdiff( names(dtRSPCPROCESSLOG), c("SYSTID", "CLIENT"))))

dtRSPCPROCESSLOG <- 
  rbindlist(
    list(dtRSPCPROCESSLOG, dtRSPCPROCESSLOG_N))
save(dtRSPCPROCESSLOG,      file = file.path("..", "..", "11_PrepData", "dtRSPCPROCESSLOG.RData"))
write.fst(dtRSPCPROCESSLOG, path = file.path("..", "..", "11_PrepData", "dtRSPCPROCESSLOG.fst"))

rm(dtRSPCLOGCHAIN_N)
rm(dtRSPCPROCESSLOG_N)

```

```{r}
dtRSPCLOG <- 
  dtRSPCLOGCHAIN[dtRSPCPROCESSLOG, on = .(SYSTID, CLIENT, LOG_ID )]
dtT <- dtRSPCLOG[CHAIN_ID == "G1_PC_TR_FI_FIGL" &
                 DATUM == "2017-10-31"          &
                 ZEIT   == "000015"]

```


```{r}
# dtRSPCLOGCHAIN  <-
#   fRead_and_Union(
#     pSID.lng = SID.lng,
#     pTable   = "RSPCLOGCHAIN",
#     pOptions = list(),
#     pFields  = fGetFields(pSYSTID = "BP1", pCLIENT = "300", pTable = "RSPCLOGCHAIN"))

# dtRSPCLOGCHAIN[, DATUM := ymd(DATUM)]

 dtRSPCCHAIN     <- 
  fRead_and_Union(
    pSIDCLNT = c("BD1100"),
    pTable   = "RSPCCHAIN",
    pOptions = list("OBJVERS = 'A'"))

dtRSPCCHAINT    <- 
  fRead_and_Union(
    # pSIDCLNT = c("BD1100"),    
    pType    = "B",
    pTable   = "RSPCCHAINT",
    pOptions = list("OBJVERS = 'A'", "AND", "LANGU = 'E'"))

# dtRSPCCHAINT    <- 
#   fReadSAPTable(
#     pSystID = "BD1",
#     pClient = "100",
#     pTable   = "RSPCCHAINT",
#     pOptions = list("OBJVERS = 'A'", "AND", "LANGU = 'E'"))

dtRSPCCHAINATTR <- 
  fRead_and_Union(
    pType    = "B",
    pTable   = "RSPCCHAINATTR",
    pOptions = list("OBJVERS = 'A'"))

dtRSPCTRIGGER   <- 
  fRead_and_Union(
    pType    = "B",
    pTable   = "RSPCTRIGGER",
    pOptions = list("OBJVERS = 'A'"))

dtRSPCTRIGGER_CHK <- 
  dcast.data.table(
    data = dtRSPCTRIGGER[PERIODIC == "X"],
    formula = VARIANTE + 
      PRDMINS + PRDHOURS + PRDDAYS + PRDWEEKS + PRDMONTHS ~ SYSTID,
    fun.aggregate = length,
    value.var = "SYSTID")                    %>%  
  .[, Total := BD1 + BA1 + BU1 + BP1]        %T>%
  setcolorder(
    c("VARIANTE", "PRDMINS", "PRDHOURS", "PRDDAYS", "PRDWEEKS", "PRDMONTHS",
      "BD1", "BA1", "BU1", "BP1", "Total"))  %T>%
  View()

dtBP1 <- 
  copy(dtSCHED)                             %>%
  setnames(paste0("BP1_", names(dtSCHED) )) %>%
  .[!is.na(BP1_CHAIN) & BP1_SYSTID == "BP1"]
 
dtRSPC <- 
  dtRSPCCHAINT[, .(SYSTID, CLIENT, CHAIN_ID, TXTLG)][
    dtRSPCCHAINATTR[, .(SYSTID, CLIENT, CHAIN_ID, TSTPNM )], 
    on = .(SYSTID, CLIENT, CHAIN_ID)]                         %>%
  dtRSPCCHAIN[ TYPE == "TRIGGER", 
               .(SYSTID, CLIENT, CHAIN_ID, VARIANTE )][
                 ., on = .(SYSTID, CLIENT, CHAIN_ID)]         %>%
  dtRSPCTRIGGER[., on = .(SYSTID, CLIENT, VARIANTE)]          %>%
  dtBP1[., on = .(BP1_CHAIN = CHAIN_ID)]

fWriteToSheet(
  dtRSPC, 
  RES, pXLSX, "CHAINS", pAppend = FALSE )
shell.exec(file.path(RES, paste0(pXLSX, ".xlsx")))

dtRSPCALIGN <- 
  dtRSPCCHAINT[dtRSPCCHAINATTR, on = .(SYSTID, CLIENT, CHAIN_ID)]
write.table(dtRSPCALIGN, 
            file = file.path(RES, "dtRSPCALIGN.csv"), row.names = F, col.names = T, sep = ";")
shell.exec(file.path(RES))

pFFN <- file.path("~", "RW", "QAR", "30_Analysis", "RSPCT.csv")

write.table(
  dtRSPCCHAINT,
  file = pFFN, sep = ";", row.names = FALSE)
shell.exec(normalizePath(pFFN))
```

# Ecc Parameter Table

```{r dtZDB_CA_GV001}
dtZDB_CA_GV001 <- 
    fRead_and_Union(
    pType    = "R",
    pTable   = "ZDB_CA_GV001",
    pOptions = list(),
    pFields  = fGetFields(pSYSTID = "RP1", pCLIENT = "300", pTable = "ZDB_CA_GV001"))

fWriteToSheet(
  dtZDB_CA_GV001, 
  RES, pXLSX, "ZDB_CA_GV001", pAppend = FALSE )
shell.exec(file.path(RES, paste0(pXLSX, ".xlsx")))  

```


## Transports
Check the failures

```{r Transport}
SID.lng  <- c("BA1300", "BP1300")
SID.sht  <- substr(SID.lng, 1, 3)

# 4 minutes
T1 <- Sys.time()

dtTPALOG <- 
  fRead_and_Union(
    pSIDCLNT = SID.lng,
    pTable   = "TPALOG", 
    pOptions = list("TRSTEP = 'R'", "AND", "TRKORR like 'BD%'"), 
    pFields  = fGetFields(pTable = "TPALOG"))

dtE070 <- 
  fRead_and_Union(
    pSIDCLNT = SID.lng,    
    pTable   = "E070", 
    pOptions = list("TRKORR like 'BD%'"), 
    pFields  = fGetFields(pTable = "E070"))

dtE071 <- 
  fRead_and_Union(
    pSIDCLNT = SID.lng,    
    pTable   = "E071", 
    pOptions = list("TRKORR like 'BD%'"), 
    pFields  = fGetFields(pTable = "E071"))

Sys.time() - T1
```

```{r}
# Open a specific workbook in Excel:
# xlApp <- COMCreate("Excel.Application")
# xlWbk <- xlApp$Workbooks()$Open(RES)
# 
# # Run the macro called "MyMacro"
# vxlApp$Run("MyMacro")
# 
# # Close the workbook (and save it) and quit the app:
# xlWbk$Close(TRUE)
# vxlApp$Quit()
# 
# # Release resources:
# rm(xlWbk, xlApp)
```

## Rescheduling

```{r BAPI_XBP_JOB_HEADER_MODIFY}

dtRSPC_REPLAN <- 
  read_excel(file.path("..", "..", "60_Results", "RSPC-Replan.xlsx"), 
             col_types = c(
               "text", "text", "text", 
               "text", "text", "text", "text", 
               "text", "text", "date", "date", 
               "text", "text", "text", "text", 
               "text", "text", "text", "text"))  %>%
  as.data.table()                                %>%
  .[,`:=`(SDLSTRTDT  = (format(SDLSTRTDT, "%Y%m%d")),
          SDLSTRTTM  = (format(SDLSTRTTM, "%H%M%S")))]

parms <- 
  list('EXTCOMPANY' = 'GRANDVISION', 
       'EXTPRODUCT' = 'SMARTR'     , 
       'INTERFACE'  = 'XBP'        ,
       'VERSION'    = '1.0')
conn <- 
  fGetSAPConnection(
    pSystId = dtRSPC_REPLAN[1, SYSTID],
    pClient = dtRSPC_REPLAN[1, CLIENT])

sessID <- 
  RSAPInvoke(conn, "BAPI_XMI_LOGON", parms)

sessID$SESSIONID

for (i in 1:nrow(dtRSPC_REPLAN)) {
  # start a scheduled job on different time
  parms <- 
    list('JOBCOUNT'           = dtRSPC_REPLAN[i, JOBCOUNT], 
         'JOBNAME'            = dtRSPC_REPLAN[i, JOBNAME],
         'EXTERNAL_USER_NAME' = 'FPADT',
         'JOB_HEADER'         = list('SDLSTRTDT' = dtRSPC_REPLAN[i, SDLSTRTDT],
                                     'SDLSTRTTM' = dtRSPC_REPLAN[i, SDLSTRTTM]),
         'MASK'               = list('STARTCOND' = 'X'))
  
  RSAPInvoke(conn, "BAPI_XBP_JOB_HEADER_MODIFY", parms)
  }

# copy a Scheduled Job -- SUCCESS --
parms <- list('SOURCE_JOBCOUNT'    = '0515170Q', 
              'SOURCE_JOBNAME'     = 'BI_PROCESS_TRIGGER',
              'TARGET_JOBNAME'     = 'BI_PROCESS_TRIGGER_UPG',
              'EXTERNAL_USER_NAME' = 'FPADT')
RSAPInvoke(conn, "BAPI_XBP_JOB_COPY", parms)

# Starts a Scheduled Job -- SUCCESS --
parms <- list('JOBCOUNT'           = '23351800', 
              'JOBNAME'            = 'BI_PROCESS_TRIGGER_UPG',
              'EXTERNAL_USER_NAME' = 'FPADT')
res <- RSAPInvoke(conn, "BAPI_XBP_JOB_START_ASAP", parms)

# read a Jb
parms <- list('JOBCOUNT'           = '23130600', 
              'JOBNAME'            = 'BI_PROCESS_TRIGGER_UPG',
              'EXTERNAL_USER_NAME' = 'FPADT')
res <- RSAPInvoke(conn, "BAPI_XBP_JOB_READ", parms)

# parms <- list('JOBCOUNT'           = '23130600', 
#               'JOBNAME'            = 'BI_PROCESS_TRIGGERFP',
#               'EXTERNAL_USER_NAME' = 'FPADT',
#               'JOB_HEADER'         = list('SDLSTRTDT' = '20180603',
#                                           'SDLSTRTTM' = '200000'))
# RSAPInvoke(conn, "BAPI_XBP_JOB_HEADER_MODIFY", parms)


```


```{r Pythia}

lSystID <- "BP1"

dtTXT <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BI0/TGENDER", 
    pOptions  = list("LANGU = 'E'"))

dtTXT <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BI0/TMATERIAL", 
    pOptions  = list("LANGU = 'E'"))

dtTXT <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BI0/TMATL_GROUP", 
    pOptions  = list("LANGU = 'E'"))

dtTXT <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BI0/TRF_BNDID", 
    pOptions  = list("LANGU = 'E'"))

dtTXT <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BI0/TVAL_CLASS", 
    pOptions  = list("LANGU = 'E'"))

dtTXT <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BIC/TG1BRNDTY", 
    pOptions  = list("LANGU = 'E'"))

dtTXT <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BIC/TG1COLOR", 
    pOptions  = list("LANGU = 'E'"))

dtTXT <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BIC/TG1FRMSHP", 
    pOptions  = list("LANGU = 'E'"))

dtTXT <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BIC/TG1HING", 
    pOptions  = list("LANGU = 'E'"))

dtTXT <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BIC/TG1MATRIAL", 
    pOptions  = list("LANGU = 'E'"))

dtTXT <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BIC/TG1MATYP", 
    pOptions  = list("LANGU = 'E'"))

dtTXT <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BIC/TG1RIM", 
    pOptions  = list("LANGU = 'E'"))

dtQ12 <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BIC/AG1SDPD2200", 
    pOptions  = list("CALDAY LIKE '201712%'", "AND",
                     "BILL_TYPE = 'FP'", "AND",
                     "(MATL_GROUP = '130131' OR MATL_GROUP = '140141')"),
    pFields   = list('CALDAY', 'MATERIAL', 'PLANT', 'RET_ITM', 'BILL_QTY'))

dtQ01 <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BIC/AG1SDPD2200", 
    pOptions  = list("CALDAY LIKE '201801%'", "AND",
                     "BILL_TYPE = 'FP'", "AND",
                     "(MATL_GROUP = '130131' OR MATL_GROUP = '140141')"),
    pFields   = list('CALDAY', 'MATERIAL', 'PLANT', 'RET_ITM', 'BILL_QTY'))

dtQ02 <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BIC/AG1SDPD2200", 
    pOptions  = list("CALDAY LIKE '201802%'", "AND",
                     "BILL_TYPE = 'FP'", "AND",
                     "(MATL_GROUP = '130131' OR MATL_GROUP = '140141')"),
    pFields   = list('CALDAY', 'MATERIAL', 'PLANT', 'RET_ITM', 'BILL_QTY'))

T1 <- Sys.time()
dtQGI <- 
  fReadSAPTable(
    pSystID   = lSystID, 
    pClient   = "300", 
    pTable    = "/BIC/AG1IMPD132", 
    pOptions  = list("PLANT = 'G001'",       "AND",
                     "MOVE_PLANT <> 'G001'", "AND",
                     "MOVE_PLANT <> 'G030'", "AND",
                     "MOVE_PLANT <> 'G040'"),                     
    pFields   = list('CALDAY', 'MATERIAL', 'MOVE_PLANT', 'MOVETYPE', 'QUANT_B'))
Sys.time() - T1

dtQGI_1 <- dtQGI %>%
  .[MOVETYPE %in% c("641", "643", "901", "910")] %>%
  .[, QUANT_B := fChar2Num(QUANT_B)]


```

[SAP Note](https://launchpad.support.sap.com/#/notes/1649901)
```{r Upgrade PSEUDO_D_AFTER_IMPORT_D }
dtRSADMIN   <- 
  fRead_and_Union(
    pType = "B",
    pTable   = "RSADMIN",
    pOptions = list(),
    pFields  = fGetFields(pSYSTID = "BP1", 
                          pCLIENT = "300", 
                          pTable  = "RSADMIN")) 

View(dtRSADMIN[OBJECT == "PSEUDO_D_AFTER_IMPORT_D"  , .(SYSTID, CLIENT, OBJECT, VALUE)])
View(dtRSADMIN[OBJECT == "BW_NO_AGGRJOIN_@3G1GLMP02", .(SYSTID, CLIENT, OBJECT, VALUE)])
```

```{r Upgrade RSBASIDOC }
dtRSBASIDOC_P   <- 
  fRead_and_Union(
    pEnv = "P",
    pTable   = "RSBASIDOC",
    pOptions = list(),
    pFields  = fGetFields(pSYSTID = "BP1", 
                          pCLIENT = "300", 
                          pTable  = "RSBASIDOC")) 

# View(dtRSADMIN[OBJECT == "PSEUDO_D_AFTER_IMPORT_D"  , .(SYSTID, CLIENT, OBJECT, VALUE)])
# View(dtRSADMIN[OBJECT == "BW_NO_AGGRJOIN_@3G1GLMP02", .(SYSTID, CLIENT, OBJECT, VALUE)])
```

```{r USER}

# [06-Feb-18 12:20]  Jeroen Jung:  
# DDIF_FIELDINFO_GET 
 

# SID.lng  <- c("BS1300", "BD1100","BU1300", "BA1300", "BP1300")
# SID.sht  <- substr(SID.lng, 1, 3)
 
dtUSR02 <- 
  fRead_and_Union(
    pType    = "B",
    pTable   = "USR02", 
    pOptions = list(), 
    pFields  = fGetFields(pSYSTID = "BP1", pCLIENT = "300", pTable = "USR02")[1:14])

if (pWSHT == TRUE) {
  fWriteToSheet(
    dtUSR02, 
    RES, pXLSX, "USER02", pAppend = FALSE )}
shell.exec(file.path(RES, paste0(pXLSX, ".xlsx")))